all:
    children:
        master:
            hosts:
               master[1:3].kuber.pro:
               
        worker:
            master:
                hosts:
                    worker[00:99].kuber.pro:
                    
        etcd:
            master:
                hosts:
                    etcd[1:3].kuber.pro:
                    
        proxies:
            master:
                hosts:
                   proxies[01:10].kuber.pro:
                
        management:
            master:
                hosts:
                    management[1:2].kuber.pro:
